import { generatePaletteFromColor } from '../../utils/colorUtils';
import { ColorPaletteType } from '../../types/FastUI';
import { isColorManuallyChanged } from '../../utils/colorAlgorithm';
import { ArrowUturnLeftIcon } from '@heroicons/react/24/outline';

interface ColorPaletteProps {
  type: ColorPaletteType;
  editable?: boolean;
  colors?: string[];
  selectedColor?: string;
  autoGeneratedColor?: string; // Автоматически подобранный цвет
  baseColorIndex?: number; // Индекс базового цвета для отметки
  onColorClick?: (index: number) => void;
  onColorPickerClick?: (color: string) => void;
  onResetToAuto?: () => void; // Функция сброса к автоматическому цвету
}

export function ColorPalette({ 
  type, 
  editable = false,
  colors = [], 
  selectedColor = '#E5484D',
  autoGeneratedColor,
  baseColorIndex,
  onColorClick,
  onColorPickerClick,
  onResetToAuto
}: ColorPaletteProps) {
  // Используем переданные colors, если они есть, иначе генерируем локально
  const colorArray = colors.length > 0 ? colors : generatePaletteFromColor(selectedColor, 11, 'Linear');
  
  // Отладочная информация
  console.log(`🎨 ColorPalette ${type}:`, {
    selectedColor,
    colorsLength: colors.length,
    colorArrayLength: colorArray.length,
    editable,
    baseColorIndex
  });
  
  // Проверяем, был ли цвет изменен вручную
  const isManuallyChanged = autoGeneratedColor && isColorManuallyChanged(autoGeneratedColor, selectedColor);

  return (
    <div className="color-row">
      <div 
        className={`color-picker ${type} ${editable ? 'editable' : ''}`}
      >
        {editable ? (
          <>
            <div className="color-picker-bg" style={{ backgroundColor: selectedColor }}></div>
            <input
              type="color"
              className="color-picker-input-direct"
              onChange={(e) => onColorPickerClick?.(e.target.value)}
              value={selectedColor}
            />
            {/* Кнопка сброса к автоматическому цвету */}
            {isManuallyChanged && onResetToAuto && (
              <button
                className="reset-color-button"
                onClick={(e) => {
                  e.stopPropagation();
                  onResetToAuto();
                }}
                title="Сбросить к автоматическому цвету"
              >
                <ArrowUturnLeftIcon width={16} height={16} />
              </button>
            )}
          </>
        ) : (
          <div className="color-picker-bg"></div>
        )}
      </div>
      <div className="color-palette">
        {colorArray.map((color: string, index: number) => (
          <div
            key={index}
            className={`color-shade ${baseColorIndex === index ? 'base-color' : ''}`}
            style={{ backgroundColor: color }}
            onClick={() => onColorClick?.(index)}
          >
            {/* Отметка базового цвета */}
            {baseColorIndex === index && (
              <div className="base-color-indicator"></div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}
