import { generatePaletteFromColor } from '../../utils/colorUtils';
import { ColorPaletteType } from '../../types/FastUI';
import { isColorManuallyChanged } from '../../utils/colorAlgorithm';
import { ArrowUturnLeftIcon } from '@heroicons/react/24/outline';

interface ColorPaletteProps {
  type: ColorPaletteType;
  colors: string[];
  selectedColor: string;
  autoGeneratedColor?: string; // Автоматически подобранный цвет
  baseColorIndex?: number; // Индекс базового цвета для отметки
  onColorChange: (color: string) => void; // Функция изменения цвета
  onResetToAuto?: () => void; // Функция сброса к автоматическому цвету
}

export function ColorPalette({ 
  type, 
  colors, 
  selectedColor,
  autoGeneratedColor,
  baseColorIndex,
  onColorChange,
  onResetToAuto
}: ColorPaletteProps) {
  // Проверяем, был ли цвет изменен вручную
  const isManuallyChanged = autoGeneratedColor && isColorManuallyChanged(autoGeneratedColor, selectedColor);

  return (
    <div className="color-row">
      <div className={`color-picker ${type} editable`}>
        <div className="color-picker-bg" style={{ backgroundColor: selectedColor }}></div>
        <input
          type="color"
          className="color-picker-input-direct"
          onChange={(e) => onColorChange(e.target.value)}
          value={selectedColor}
        />
        {/* Кнопка сброса к автоматическому цвету */}
        {isManuallyChanged && onResetToAuto && (
          <button
            className="reset-color-button"
            onClick={(e) => {
              e.stopPropagation();
              onResetToAuto();
            }}
            title="Сбросить к автоматическому цвету"
          >
            <ArrowUturnLeftIcon width={16} height={16} />
          </button>
        )}
      </div>
      <div className="color-palette">
        {colors.map((color: string, index: number) => (
          <div
            key={index}
            className={`color-shade ${baseColorIndex === index ? 'base-color' : ''}`}
            style={{ backgroundColor: color }}
          >
            {/* Отметка базового цвета */}
            {baseColorIndex === index && (
              <div className="base-color-indicator"></div>
            )}
          </div>
        ))}

      </div>
    </div>
  );
}
