import { useState, useEffect, useCallback } from "react";
import { Header, Navigation, Settings, ColorPalette, AddColorRow, Footer, KeyPointsInputs } from "./index";
import { CurveSelector, CurveType } from "./CurveSelector";
import { ColorPaletteType, ColorPaletteData } from "../../types/FastUI";
import { generatePaletteFromColor } from "../../utils/colorUtils";
import { generateStatusColors } from "../../utils/colorAlgorithm";
import { CurveSettings } from "../../types/curveEditor";
import { generateVisuallyUniformLightness } from "../../utils/curveUtils";
import { generateApcaValuesByType, convertApcaArrayToLightness } from "../../utils/apcachConverter";
import "../../styles/FastUI.css";

export function FastUIDesign() {
  const [selectedScale, setSelectedScale] = useState<'Linear' | 'Semantic'>('Linear');
  const [selectedNaming, setSelectedNaming] = useState('50,100,150...');
  const [curveType, setCurveType] = useState<CurveType>('custom');
  const [selectedColors, setSelectedColors] = useState<Record<ColorPaletteType, string>>(() => {
    const brandColor = '#3b82f6';
    const statusColors = generateStatusColors(brandColor);
    return {
      brand: brandColor,
      ...statusColors
    };
  });
  
  const [autoGeneratedColors, setAutoGeneratedColors] = useState<Record<ColorPaletteType, string>>(() => {
    const brandColor = '#3b82f6';
    const statusColors = generateStatusColors(brandColor);
    return {
      brand: brandColor,
      ...statusColors
    };
  });
  
  const [manuallyChangedColors, setManuallyChangedColors] = useState<Set<ColorPaletteType>>(new Set());
  const [colorPalettes, setColorPalettes] = useState<Record<ColorPaletteType, string[]>>({
    brand: [],
    accent: [],
    info: [],
    success: [],
    error: [],
    warning: [],
    neutral: []
  });

           // Настройки кривых
         const [lightnessCurve, setLightnessCurve] = useState<CurveSettings>(() => {
           const steps = selectedScale === 'Linear' ? 11 : 12;
           // Генерируем APCA значения для бренд-цвета
           const apcaValues = generateApcaValuesByType('brand', steps);
           const lightnessValues = convertApcaArrayToLightness(apcaValues);
           
           const keyPoints = [];
           for (let i = 0; i < steps; i++) {
             keyPoints.push({
               id: `point-${i}`,
               y: lightnessValues[i],
               isApcach: true
             });
           }
           
           return {
             mode: 'keypoints',
             keyPoints: keyPoints,
             bezierCurve: {
               startPoint: { x: 0, y: 0.98 },
               endPoint: { x: 1, y: 0.1 },
               controlPoint1: { x: 0.33, y: 0.33 },
               controlPoint2: { x: 0.66, y: 0.66 }
             },
             steps: steps
           };
         });



           // Обновление количества шагов при изменении масштаба
         useEffect(() => {
           const newSteps = selectedScale === 'Linear' ? 11 : 12;
           setLightnessCurve(prev => {
             // Создаем новые ключевые точки с APCA значениями
             const apcaValues = generateApcaValuesByType('brand', newSteps);
             const lightnessValues = convertApcaArrayToLightness(apcaValues);
             
             const newKeyPoints = [];
             for (let i = 0; i < newSteps; i++) {
               newKeyPoints.push({
                 id: `point-${i}`,
                 y: lightnessValues[i],
                 isApcach: true
               });
             }
             
             return { 
               ...prev, 
               steps: newSteps,
               keyPoints: newKeyPoints
             };
           });
         
         }, [selectedScale]);

  // Генерация автоматических цветов на основе бренд-цвета
  const generateAutoColors = (brandColor: string) => {
    console.log('Генерируем автоматические цвета для:', brandColor);
    const statusColors = generateStatusColors(brandColor);
    console.log('Сгенерированные статусные цвета:', statusColors);
    
    // Обновляем autoGeneratedColors
    setAutoGeneratedColors(prev => ({
      ...prev,
      ...statusColors
    }));

    // Обновляем selectedColors и палитры в одном месте для оптимизации
    setSelectedColors(prev => {
      const updated = { ...prev };
      const colorsToUpdate: Partial<Record<ColorPaletteType, string>> = {};
      
      Object.entries(statusColors).forEach(([type, color]) => {
        if (!manuallyChangedColors.has(type as ColorPaletteType)) {
          updated[type as ColorPaletteType] = color;
          colorsToUpdate[type as ColorPaletteType] = color;
        }
      });
      
      console.log('Обновленные selectedColors:', updated);
      
                   // Обновляем палитры для измененных цветов
             if (Object.keys(colorsToUpdate).length > 0) {
               setColorPalettes(prevPalettes => {
                 const updatedPalettes = { ...prevPalettes };
                 Object.entries(colorsToUpdate).forEach(([type, color]) => {
                   updatedPalettes[type as ColorPaletteType] = generatePaletteFromColor(
                     color, 
                     selectedScale === 'Linear' ? 11 : 12, 
                     selectedScale, 
                     lightnessCurve,
                     undefined,
                     { useApcach: true, colorType: type as ColorPaletteType }
                   );
                 });
                 console.log('Обновленные палитры после генерации:', updatedPalettes);
                 return updatedPalettes;
               });
             }
      
      return updated;
    });
  };

  // Функция debounce
  const debounce = (func: Function, delay: number) => {
    let timeoutId: number;
    return (...args: any[]) => {
      clearTimeout(timeoutId);
      timeoutId = setTimeout(() => func(...args), delay);
    };
  };

           // Debounced функция для обновления палитр
         const debouncedUpdatePalette = useCallback(
           debounce((type: ColorPaletteType, color: string) => {
             setColorPalettes(prev => ({
               ...prev,
               [type]: generatePaletteFromColor(color, selectedScale === 'Linear' ? 11 : 12, selectedScale, lightnessCurve, undefined, { useApcach: true, colorType: type })
             }));
           }, 100),
           [selectedScale, lightnessCurve]
         );

  // Debounced функция для генерации автоматических цветов
  const debouncedGenerateAutoColors = useCallback(
    debounce((brandColor: string) => {
      generateAutoColors(brandColor);
    }, 150),
    []
  );

  // Обработчик изменения цвета
  const handleColorChange = (type: ColorPaletteType, color: string) => {
    console.log('Изменяем цвет:', type, 'на:', color);
    
    setSelectedColors(prev => ({ ...prev, [type]: color }));
    
    // Если это не бренд-цвет, отмечаем как измененный вручную
    if (type !== 'brand') {
      setManuallyChangedColors(prev => new Set(prev).add(type));
    }
    
    // Если это бренд-цвет, используем debounced генерацию
    if (type === 'brand') {
      debouncedGenerateAutoColors(color);
    } else {
      // Для всех остальных цветов используем debounced обновление палитры
      debouncedUpdatePalette(type, color);
    }
  };

  // Сброс к автоматически сгенерированному цвету
  const handleResetToAuto = (type: ColorPaletteType) => {
    console.log('Сбрасываем цвет:', type, 'к автоматическому:', autoGeneratedColors[type]);
    
    setSelectedColors(prev => ({
      ...prev,
      [type]: autoGeneratedColors[type]
    }));
    setManuallyChangedColors(prev => {
      const newSet = new Set(prev);
      newSet.delete(type);
      return newSet;
    });
    
               // Принудительно обновляем палитру для сброшенного цвета
           setColorPalettes(prev => ({
             ...prev,
             [type]: generatePaletteFromColor(autoGeneratedColors[type], selectedScale === 'Linear' ? 11 : 12, selectedScale, lightnessCurve, undefined, { useApcach: true, colorType: type })
           }));
  };



  // Обработчик изменения ключевых точек
  const handleKeyPointChange = (pointId: string, newValue: string) => {
    const value = parseFloat(newValue);
    if (isNaN(value) || value < 0 || value > 1) return;
    
    let newKeyPoints = lightnessCurve.keyPoints.map(point =>
      point.id === pointId ? { ...point, y: value } : point
    );
    
    // Если это линейная или S-образная кривая, пересчитываем промежуточные точки
    if (curveType === 'linear' || curveType === 's-curve') {
      const firstPoint = newKeyPoints[0];
      const lastPoint = newKeyPoints[newKeyPoints.length - 1];
      
      if (curveType === 'linear') {
        // Визуально равномерная интерполяция между крайними точками
        const visuallyUniformValues = generateVisuallyUniformLightness(
          firstPoint.y, 
          lastPoint.y, 
          newKeyPoints.length
        );
        
        for (let i = 1; i < newKeyPoints.length - 1; i++) {
          newKeyPoints[i] = {
            ...newKeyPoints[i],
            y: visuallyUniformValues[i]
          };
        }
      } else if (curveType === 's-curve') {
        // S-образная интерполяция
        for (let i = 1; i < newKeyPoints.length - 1; i++) {
          const t = i / (newKeyPoints.length - 1);
          const sCurve = 3 * Math.pow(t, 2) - 2 * Math.pow(t, 3); // S-образная функция
          newKeyPoints[i] = {
            ...newKeyPoints[i],
            y: firstPoint.y - (firstPoint.y - lastPoint.y) * sCurve
          };
        }
      }
    }
    // В кастомном режиме не изменяем промежуточные точки - они остаются как есть
    
    const newSettings = { ...lightnessCurve, keyPoints: newKeyPoints };
    setLightnessCurve(newSettings);
  };



  // Конфигурация палитр
  const paletteConfigs: ColorPaletteData[] = [
    { type: 'brand', name: 'Brand', selectedColor: selectedColors.brand },
    { type: 'accent', name: 'Accent', selectedColor: selectedColors.accent },
    { type: 'info', name: 'Info', selectedColor: selectedColors.info },
    { type: 'success', name: 'Success', selectedColor: selectedColors.success },
    { type: 'error', name: 'Error', selectedColor: selectedColors.error },
    { type: 'warning', name: 'Warning', selectedColor: selectedColors.warning },
    { type: 'neutral', name: 'Neutral', selectedColor: selectedColors.neutral }
  ];

           // Инициализация палитр при монтировании
         useEffect(() => {
           const initialPalettes: Record<ColorPaletteType, string[]> = {
             brand: generatePaletteFromColor(selectedColors.brand, selectedScale === 'Linear' ? 11 : 12, selectedScale, lightnessCurve, undefined, { useApcach: true, colorType: 'brand' }),
             accent: generatePaletteFromColor(selectedColors.accent, selectedScale === 'Linear' ? 11 : 12, selectedScale, lightnessCurve, undefined, { useApcach: true, colorType: 'accent' }),
             info: generatePaletteFromColor(selectedColors.info, selectedScale === 'Linear' ? 11 : 12, selectedScale, lightnessCurve, undefined, { useApcach: true, colorType: 'info' }),
             success: generatePaletteFromColor(selectedColors.success, selectedScale === 'Linear' ? 11 : 12, selectedScale, lightnessCurve, undefined, { useApcach: true, colorType: 'success' }),
             error: generatePaletteFromColor(selectedColors.error, selectedScale === 'Linear' ? 11 : 12, selectedScale, lightnessCurve, undefined, { useApcach: true, colorType: 'error' }),
             warning: generatePaletteFromColor(selectedColors.warning, selectedScale === 'Linear' ? 11 : 12, selectedScale, lightnessCurve, undefined, { useApcach: true, colorType: 'warning' }),
             neutral: generatePaletteFromColor(selectedColors.neutral, selectedScale === 'Linear' ? 11 : 12, selectedScale, lightnessCurve, undefined, { useApcach: true, colorType: 'neutral' })
           };
           setColorPalettes(initialPalettes);
         }, [lightnessCurve]);

  // Обновление палитр при изменении цветов, масштаба или кривых
  useEffect(() => {
    console.log('Обновляем палитры для цветов:', selectedColors);
    const updatedPalettes: Record<ColorPaletteType, string[]> = {
      brand: generatePaletteFromColor(selectedColors.brand, selectedScale === 'Linear' ? 11 : 12, selectedScale, lightnessCurve, undefined, { useApcach: true, colorType: 'brand' }),
      accent: generatePaletteFromColor(selectedColors.accent, selectedScale === 'Linear' ? 11 : 12, selectedScale, lightnessCurve, undefined, { useApcach: true, colorType: 'accent' }),
      info: generatePaletteFromColor(selectedColors.info, selectedScale === 'Linear' ? 11 : 12, selectedScale, lightnessCurve, undefined, { useApcach: true, colorType: 'info' }),
      success: generatePaletteFromColor(selectedColors.success, selectedScale === 'Linear' ? 11 : 12, selectedScale, lightnessCurve, undefined, { useApcach: true, colorType: 'success' }),
      error: generatePaletteFromColor(selectedColors.error, selectedScale === 'Linear' ? 11 : 12, selectedScale, lightnessCurve, undefined, { useApcach: true, colorType: 'error' }),
      warning: generatePaletteFromColor(selectedColors.warning, selectedScale === 'Linear' ? 11 : 12, selectedScale, lightnessCurve, undefined, { useApcach: true, colorType: 'warning' }),
      neutral: generatePaletteFromColor(selectedColors.neutral, selectedScale === 'Linear' ? 11 : 12, selectedScale, lightnessCurve, undefined, { useApcach: true, colorType: 'neutral' })
    };
    console.log('Сгенерированные палитры:', updatedPalettes);
    setColorPalettes(updatedPalettes);
  }, [selectedColors, selectedScale, lightnessCurve]);

  // Генерация автоматических цветов при изменении бренд-цвета
  useEffect(() => {
    generateAutoColors(selectedColors.brand);
  }, [selectedColors.brand]);



  return (
    <div className="fast-ui-design">
      <Header />
      <div className="body">
        <div className="body-content">
          <Navigation />
          <Settings 
            selectedScale={selectedScale} 
            selectedNaming={selectedNaming}
            onScaleChange={setSelectedScale}
            onNamingChange={setSelectedNaming}
          />
          
          <div className="color-schemes">
            {paletteConfigs.map(({ type, selectedColor }) => (
              <ColorPalette
                key={type}
                type={type}
                selectedColor={selectedColor}
                colors={colorPalettes[type]}
                autoGeneratedColor={autoGeneratedColors[type]}
                onColorChange={(color) => handleColorChange(type, color)}
                onResetToAuto={() => handleResetToAuto(type)}
              />
            ))}
            <AddColorRow placeholderCount={selectedScale === 'Linear' ? 11 : 12} />
            <div className="keypoints-inputs-row">
              <CurveSelector
                currentCurve={lightnessCurve}
                onCurveChange={setLightnessCurve}
                onCurveTypeChange={setCurveType}
                curveType={curveType}
              />
              <div className="keypoints-inputs-container">
                <KeyPointsInputs 
                  keyPoints={lightnessCurve.keyPoints}
                  onKeyPointChange={handleKeyPointChange}
                  curveType={curveType}
                />
              </div>
            </div>
          </div>

          <Footer />
        </div>
      </div>
    </div>
  );
}
