import React, { useState, useEffect } from "react";
import { Header, Navigation, Settings, ColorPalette, AddColorRow, Footer, KeyPointsInputs } from "./index";
import { CurveEditor } from "./CurveEditor";
import { ColorPaletteType, ColorPaletteData } from "../../types/FastUI";
import { generatePaletteFromColor } from "../../utils/colorUtils";
import { generateStatusColors } from "../../utils/colorAlgorithm";
import { CurveSettings } from "../../types/curveEditor";
import { bezierToKeyPoints } from "../../utils/curveUtils";
import "../../styles/FastUI.css";

export function FastUIDesign() {
  const [selectedScale, setSelectedScale] = useState<'Linear' | 'Semantic'>('Linear');
  const [selectedNaming, setSelectedNaming] = useState('50,100,150...');
  const [selectedColors, setSelectedColors] = useState<Record<ColorPaletteType, string>>({
    brand: '#3b82f6',
    accent: '#f59e0b',
    info: '#06b6d4',
    success: '#10b981',
    error: '#ef4444',
    warning: '#f59e0b',
    neutral: '#6b7280'
  });
  
  const [autoGeneratedColors, setAutoGeneratedColors] = useState<Record<ColorPaletteType, string>>({
    brand: '#3b82f6',
    accent: '#f59e0b',
    info: '#06b6d4',
    success: '#10b981',
    error: '#ef4444',
    warning: '#f59e0b',
    neutral: '#6b7280'
  });
  
  const [manuallyChangedColors, setManuallyChangedColors] = useState<Set<ColorPaletteType>>(new Set());
  const [colorPalettes, setColorPalettes] = useState<Record<ColorPaletteType, string[]>>({
    brand: [],
    accent: [],
    info: [],
    success: [],
    error: [],
    warning: [],
    neutral: []
  });

  // Настройки кривых
  const [lightnessCurve, setLightnessCurve] = useState<CurveSettings>({
    mode: 'keypoints',
    keyPoints: bezierToKeyPoints({
      startPoint: { x: 0, y: 0.98 },
      endPoint: { x: 1, y: 0.08 },
      controlPoint1: { x: 0.33, y: 0.8 },
      controlPoint2: { x: 0.66, y: 0.3 }
    }, selectedScale === 'Linear' ? 11 : 12),
    bezierCurve: {
      startPoint: { x: 0, y: 0.98 },
      endPoint: { x: 1, y: 0.08 },
      controlPoint1: { x: 0.33, y: 0.8 },
      controlPoint2: { x: 0.66, y: 0.3 }
    },
    steps: selectedScale === 'Linear' ? 11 : 12
  });

  const [chromaCurve, setChromaCurve] = useState<CurveSettings>({
    mode: 'bezier',
    keyPoints: [],
    bezierCurve: {
      startPoint: { x: 0, y: 0.1 },
      endPoint: { x: 1, y: 0.1 },
      controlPoint1: { x: 0.5, y: 1.0 },
      controlPoint2: { x: 0.5, y: 1.0 }
    },
    steps: selectedScale === 'Linear' ? 11 : 12
  });

  // Обновление количества шагов при изменении масштаба
  useEffect(() => {
    const newSteps = selectedScale === 'Linear' ? 11 : 12;
    setLightnessCurve(prev => ({ 
      ...prev, 
      steps: newSteps,
      keyPoints: bezierToKeyPoints(prev.bezierCurve, newSteps)
    }));
    setChromaCurve(prev => ({ ...prev, steps: newSteps }));
  }, [selectedScale]);

  // Генерация автоматических цветов на основе бренд-цвета
  const generateAutoColors = (brandColor: string) => {
    const statusColors = generateStatusColors(brandColor);
    
    setAutoGeneratedColors(prev => ({
      ...prev,
      ...statusColors
    }));

    // Обновляем selectedColors только для тех цветов, которые не были изменены вручную
    // НЕ обновляем бренд-цвет - он должен оставаться пользовательским
    setSelectedColors(prev => {
      const updated = { ...prev };
      Object.entries(statusColors).forEach(([type, color]) => {
        if (!manuallyChangedColors.has(type as ColorPaletteType)) {
          updated[type as ColorPaletteType] = color;
        }
      });
      return updated;
    });
  };

  // Обработчик изменения цвета
  const handleColorChange = (type: ColorPaletteType, color: string) => {
    setSelectedColors(prev => ({ ...prev, [type]: color }));
    
    // Если это не бренд-цвет, отмечаем как измененный вручную
    if (type !== 'brand') {
      setManuallyChangedColors(prev => new Set(prev).add(type));
    }
    
    // Если это бренд-цвет, генерируем автоматические цвета
    if (type === 'brand') {
      generateAutoColors(color);
    }
  };

  // Сброс к автоматически сгенерированному цвету
  const handleResetToAuto = (type: ColorPaletteType) => {
    setSelectedColors(prev => ({
      ...prev,
      [type]: autoGeneratedColors[type]
    }));
    setManuallyChangedColors(prev => {
      const newSet = new Set(prev);
      newSet.delete(type);
      return newSet;
    });
  };

  // Получение индекса базового цвета в палитре
  const getBaseColorIndex = (selectedColor: string, colorPalette: string[]): number => {
    return colorPalette.findIndex(color => color === selectedColor);
  };

  // Обработчик изменения ключевых точек
  const handleKeyPointChange = (pointId: string, newValue: string) => {
    const value = parseFloat(newValue);
    if (isNaN(value) || value < 0 || value > 1) return;
    
    const newKeyPoints = lightnessCurve.keyPoints.map(point =>
      point.id === pointId ? { ...point, y: value } : point
    );
    const newSettings = { ...lightnessCurve, keyPoints: newKeyPoints };
    console.log('Updating lightness curve:', newSettings);
    setLightnessCurve(newSettings);
  };



  // Конфигурация палитр
  const paletteConfigs: ColorPaletteData[] = [
    { type: 'brand', name: 'Brand', selectedColor: selectedColors.brand },
    { type: 'accent', name: 'Accent', selectedColor: selectedColors.accent },
    { type: 'info', name: 'Info', selectedColor: selectedColors.info },
    { type: 'success', name: 'Success', selectedColor: selectedColors.success },
    { type: 'error', name: 'Error', selectedColor: selectedColors.error },
    { type: 'warning', name: 'Warning', selectedColor: selectedColors.warning },
    { type: 'neutral', name: 'Neutral', selectedColor: selectedColors.neutral }
  ];

  // Инициализация палитр при монтировании
  useEffect(() => {
    const initialPalettes: Record<ColorPaletteType, string[]> = {
      brand: generatePaletteFromColor(selectedColors.brand, selectedScale === 'Linear' ? 11 : 12, selectedScale, lightnessCurve),
      accent: generatePaletteFromColor(selectedColors.accent, selectedScale === 'Linear' ? 11 : 12, selectedScale, lightnessCurve),
      info: generatePaletteFromColor(selectedColors.info, selectedScale === 'Linear' ? 11 : 12, selectedScale, lightnessCurve),
      success: generatePaletteFromColor(selectedColors.success, selectedScale === 'Linear' ? 11 : 12, selectedScale, lightnessCurve),
      error: generatePaletteFromColor(selectedColors.error, selectedScale === 'Linear' ? 11 : 12, selectedScale, lightnessCurve),
      warning: generatePaletteFromColor(selectedColors.warning, selectedScale === 'Linear' ? 11 : 12, selectedScale, lightnessCurve),
      neutral: generatePaletteFromColor(selectedColors.neutral, selectedScale === 'Linear' ? 11 : 12, selectedScale, lightnessCurve)
    };
    setColorPalettes(initialPalettes);
  }, [lightnessCurve]);

  // Обновление палитр при изменении цветов, масштаба или кривых
  useEffect(() => {
    const updatedPalettes: Record<ColorPaletteType, string[]> = {
      brand: generatePaletteFromColor(selectedColors.brand, selectedScale === 'Linear' ? 11 : 12, selectedScale, lightnessCurve),
      accent: generatePaletteFromColor(selectedColors.accent, selectedScale === 'Linear' ? 11 : 12, selectedScale, lightnessCurve),
      info: generatePaletteFromColor(selectedColors.info, selectedScale === 'Linear' ? 11 : 12, selectedScale, lightnessCurve),
      success: generatePaletteFromColor(selectedColors.success, selectedScale === 'Linear' ? 11 : 12, selectedScale, lightnessCurve),
      error: generatePaletteFromColor(selectedColors.error, selectedScale === 'Linear' ? 11 : 12, selectedScale, lightnessCurve),
      warning: generatePaletteFromColor(selectedColors.warning, selectedScale === 'Linear' ? 11 : 12, selectedScale, lightnessCurve),
      neutral: generatePaletteFromColor(selectedColors.neutral, selectedScale === 'Linear' ? 11 : 12, selectedScale, lightnessCurve)
    };
    setColorPalettes(updatedPalettes);
  }, [selectedColors, selectedScale, lightnessCurve]);

  // Генерация автоматических цветов при изменении бренд-цвета
  useEffect(() => {
    generateAutoColors(selectedColors.brand);
  }, [selectedColors.brand]);

  // Инициализация: помечаем бренд-цвет как измененный вручную, чтобы не показывать стрелочку сброса
  useEffect(() => {
    setManuallyChangedColors(prev => {
      const newSet = new Set(prev);
      newSet.add('brand');
      return newSet;
    });
  }, []);

  return (
    <div className="fast-ui-design">
      <Header />
      <div className="body">
        <div className="body-content">
          <Navigation />
          <Settings 
            selectedScale={selectedScale} 
            selectedNaming={selectedNaming}
            onScaleChange={setSelectedScale}
            onNamingChange={setSelectedNaming}
          />
          
          <div className="color-schemes">
            {paletteConfigs.map(({ type, selectedColor }) => (
              <ColorPalette
                key={type}
                type={type}
                selectedColor={selectedColor}
                colors={colorPalettes[type]}
                autoGeneratedColor={autoGeneratedColors[type]}
                onColorChange={(color) => handleColorChange(type, color)}
                onResetToAuto={() => handleResetToAuto(type)}
                baseColorIndex={getBaseColorIndex(selectedColor, colorPalettes[type])}
              />
            ))}
            <AddColorRow placeholderCount={selectedScale === 'Linear' ? 11 : 12} />
            <KeyPointsInputs 
              keyPoints={lightnessCurve.keyPoints}
              onKeyPointChange={handleKeyPointChange}
            />
          </div>

          <Footer />
        </div>
      </div>
    </div>
  );
}
